#!/usr/bin/env python

import requests
import json
import tools
import record_request
import sys

def pull_records(name, birthday, apartment, credentials):
    payload = {
            'mrnOrName':name,
            'name':name,
            'birthDate':birthday
            }
    
    RECORDS_ADDRESS = 'https://www.lds.org/mls/mbr/services/records/request/find-member?lang=eng'
    PULL_ADDRESS = 'https://www.lds.org/mls/mbr/services/records/request/move-household?lang=eng'

    headers = { 'accept':'application/json, text/plain, */*', }
    response = session.post(url = RECORDS_ADDRESS, data = json.dumps(payload), cookies = credentials, headers = headers)
    assert (response.response_code == 200)

    decoded = json.loads(response.text)
    request = record_request.buildRequestBody(response.text, apartment)
    response = session.put(url = pullAddress, data = json.dumps(request), cookies = credentials, headers = headers)
    assert (response.response_code == 200)

    decoded = json.loads(response.text)
    

username = sys.argv[1]
password = sys.argv[2]

session = requests.session()
credentials = tools.login(session, username, password)

output = ""

for line in sys.stdin:

    data = line.rstrip().split(', ')
    name = data[0]
    birthday = data[1]
    apartment = data[2]

    try:
        result = pull_records(name, birthday, apartment, credentials)

    except(AssertionError, ValueError, KeyError, TypeError):
        #append a message notifying the error
        result = ', '.join(name, 'error', '\n')
        
    output = output + result

sys.stdout.write(output)
